### ISSUE TITLE
I cannot state the problem.

### ISSUE THREAD

**Issue by limelect** [halilhanbadem/Java-ile-Delphi-Android-Uygulama-Tetikleme#1]
On D10.2.1 cannot compile even after deleting and left with dpr and pas.
trying to debug why button dose not trigger on release compile.
some thing is wrong cannot compile debug. rtl.bpl error.

**Comment by limelect** [comment]
I do not understand your comment.
As the button did not work in release mode
i tried to debug . The compiler could not compile.

After 4'th time it did send the apk to my phone and debug.
on   TAndroidHelper.AlarmManager.&set(TJAlarmManager.JavaClass.RTC_WAKEUP, getTimeAfterInSecs(30),
    PendingIntent);
 it  dumped E:\Delphi_Programs\Halil Han\Java-ile-Delphi-Android-Uygulama-Tetikleme-master\Example\AndroidSource\libDeneme.so to Delphi.
strange.
How ever running the program ,apk, without Delphi the button did nothing as in release mode

**Comment by halilhanbadem** [comment]
When I go to the computer, I will deal with your problem.

**Comment by halilhanbadem** [comment]
Hello there! 

First of all, let me tell you a little bit about triggering. First we write a code block with java. Then we import it to Delphi.

> NOTE: You should review this source for this java file. There are a few little details.
> 
> http://delphifmandroid.blogspot.com.tr/2016/02/alarmmanager-rad-studio.html

In order to continue, we call our function, which we have defined as public in Java, via Delphi. If your actions are successful, you need to:

Open the program and press the button and close the program. After a while the program will open automatically.

> The source I refer to is;
> 
> http://delphifmandroid.blogspot.com.tr/2016/02/alarmmanager-rad-studio.html

_**If you can explain the problem better, try to be more helpful.**_


> In addition, you can find detailed explanations on the link below. There must be something you do wrong. I do not think it's related to Delphi versions.
> 
> http://www.delphican.com/java-ile-android-program-tetikleme.html

Download translation plugin to browser :)

![image](https://user-images.githubusercontent.com/17130294/39408967-1d2e4f02-4be7-11e8-9c3e-e57b543e7e91.png)


Best regards,
Halil Han Badem.

**Comment by limelect** [comment]
I understand now thanks
